### ISSUE TITLE
I need ur help

### ISSUE THREAD

**Issue by Assia55** [Atamg1994/atamg1994.github.io#1]
I'm reaching out because I need your expertise with the [AutoTranslator](https://github.com/bbepis/XUnity.AutoTranslator) tool. I'm trying to translate a game into Arabic, but I'm encountering issues with right-to-left (RTL) text rendering. Could you please help me resolve this error? Your guidance would be greatly appreciated!

**Comment by Atamg1994** [comment]
So how exactly can I help you?

**Comment by Atamg1994** [comment]
I have no idea how to display text correctly.. I haven’t worked with Arabic...

**Comment by Assia55** [comment]
Thnak for reply i soleved the problme by build my custom server based on google thanks a lot
